USE [BD_CHALENGE]
GO

/****** Object:  Table [dbo].[TB_CURTIDAS]    Script Date: 21/10/2020 19:04:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_CURTIDAS](
	[ID_CURTIDA] [int] IDENTITY(1,1) NOT NULL,
	[IP_CURTIDA] [varchar](20) NULL,
	[QTDE_CURTIDA] [int] NOT NULL,
	[BROWNSER] [varchar](50) NULL,
 CONSTRAINT [PK_TB_CURTIDAS] PRIMARY KEY CLUSTERED 
(
	[ID_CURTIDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


